name: eechart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  bip39: ^1.0.6
  rxdart: ^0.27.1
  fluttertoast: ^8.0.7
  dotted_border: ^2.0.0
  collection: ^1.15.0
  flutter_slidable: ^0.6.0
  lpinyin: ^2.0.3
  azlistview: ^2.0.0-nullsafety.0
  flutterlifecyclehooks: ^2.0.0-nullsafety.0
  bubble: ^1.2.1
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.0+3
  flutter_image_compress: ^1.0.0
  image_gallery_saver: ^1.6.9
  photo_view: ^0.11.1
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  device_info: ^2.0.2
  cached_network_image: ^3.0.0
  record: ^2.1.1
#  audioplayers: ^0.19.0
  just_audio: ^0.7.5
#  flutter_sound: ^8.1.4
  lottie: ^1.0.1
#  custom_pop_up_menu: ^1.2.0
#  flutter_keyboard_size: ^1.0.0+3
#  flutter_keyboard_visibility: ^5.0.2
  keyboard_utils: ^1.3.0
  sprintf: ^6.0.0
  event_bus: ^2.0.0
#  flutter_isolate: ^2.0.0
#  isolate_handler: ^1.0.0
#  worker_manager: ^4.0.2
#  isolate:
#    git:
#      url: https://github.com/dart-lang/isolate.git
#  indexed_list_view: ^2.0.0
  scroll_to_index: ^2.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  images_picker: ^1.2.4
  media_info: ^0.7.0
  synchronized: ^3.0.0
  chewie: ^1.2.2
  video_player: ^2.1.6
  flutter_fgbg: ^0.1.0
  qr_flutter: ^4.0.0
  flutter_qr_reader:
    git:
      url: https://github.com/hrxiang/flutter_qr_reader.git
#  flutter_openim_sdk:
#    git:
#      url: https://github.com/OpenIMSDK/Open-IM-SDK-Flutter.git
  flutter_openim_sdk:
    path: ../Open-IM-SDK-Flutter
#  flutter_qr_reader:
#    path: ../flutter_qr_reader-1.0.5
#  material_tag_editor: ^0.1.1
  extended_text_field: ^8.0.0
#  rich_text_controller: ^1.3.0
  flutter_background:
    git:
      url: https://github.com/hrxiang/flutter_background.git
  #  flutter_webrtc: ^0.6.5
#  scrollable_positioned_list: ^0.2.0-nullsafety.0
  focus_detector: ^2.0.0
#  visibility_detector: ^0.2.0
#  firebase_core: ^1.4.0
#  firebase_messaging: ^10.0.4
#  flutter_local_notifications: ^6.1.0
  file_picker: ^3.0.3
  #  wechat_assets_picker: ^5.5.6
  wechat_camera_picker: ^2.3.0
#  webview_flutter: ^2.0.12
  flutter_inappwebview: ^5.3.2
  map_launcher: ^2.1.1
  flutter_svg: ^0.22.0
  open_file: ^3.2.1
#  flutter_bmflocation: ^1.0.4
#  flutter_baidu_mapapi_map: ^2.0.1
#  flutter_baidu_mapapi_search: ^2.0.1
#  flutter_baidu_mapapi_utils: ^2.0.1
#  flutter_bmflocation:
#    path: ../baidu-map/flutter_bmflocation-1.0.4
#  flutter_baidu_mapapi_map:
#    path: ../baidu-map/flutter_baidu_mapapi_map-2.0.0
#  flutter_baidu_mapapi_search:
#    path: ../baidu-map/flutter_baidu_mapapi_search-2.0.0
#  flutter_baidu_mapapi_utils:
#    path: ../baidu-map/flutter_baidu_mapapi_utils-2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - assets/images/
    - assets/data/
    - assets/anim/
    - assets/images/ic_login_ic1.webp
    - assets/images/ic_login_ic2.webp
    - assets/images/ic_login_ic3.webp
    - assets/images/ic_login_ic4.webp
    - assets/images/ic_login_ic5.webp
    - assets/images/ic_login_ic6.webp
    - assets/images/ic_register_ic1.webp
    - assets/images/ic_register_ic2.webp
    - assets/images/ic_register_ic3.webp
    - assets/images/ic_backup_ic1.webp
    - assets/images/ic_backup_ic2.webp
    - assets/images/ic_back.webp
    - assets/images/ic_add.webp
    - assets/images/ic_tab1_nor.webp
    - assets/images/ic_tab1_sel.webp
    - assets/images/ic_tab2_nor.webp
    - assets/images/ic_tab2_sel.webp
    - assets/images/ic_tab3_nor.webp
    - assets/images/ic_tab3_sel.webp
    - assets/images/ic_search.webp
    - assets/images/ic_new_friend.webp
    - assets/images/ic_mine_ic1.webp
    - assets/images/ic_mine_ic2.webp
    - assets/images/ic_mine_ic3.webp
    - assets/images/ic_mine_ic4.webp
    - assets/images/ic_speak.webp
    - assets/images/ic_add_blue.webp
    - assets/images/ic_menu_copy.webp
    - assets/images/ic_menu_del.webp
    - assets/images/ic_menu_forward.webp
    - assets/images/ic_menu_revoke.webp
    - assets/images/ic_camera.webp
    - assets/images/ic_album.webp
    - assets/images/ic_voice_blue.webp
    - assets/images/ic_voice_black.webp
    - assets/images/ic_voice_ic1.webp
    - assets/images/ic_more.webp
    - assets/images/ic_next.webp
    - assets/images/ic_switch_open.webp
    - assets/images/ic_switch_close.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_clear.webp
    - assets/images/ic_search_result_ic1.webp
    - assets/images/ic_msg.webp
    - assets/images/ic_pic_load_error.webp
    - assets/images/ic_video_play.webp
    - assets/images/ic_msg_error.webp
    - assets/images/tool_flashlight_close.png
    - assets/images/tool_flashlight_open.png
    - assets/images/tool_img.png
    - assets/images/tool_qrcode.png
    - assets/images/ic_radio_nor.webp
    - assets/images/ic_radio_sel.webp
    - assets/images/ic_group_chat1.webp
    - assets/images/ic_group_chat2.webp
    - assets/images/ic_group_chat3.webp
    - assets/images/ic_group_chat4.webp
    - assets/images/ic_group_member_add.webp
    - assets/images/ic_group_member_sub.webp
    - assets/images/ic_group_member_more.webp
    - assets/images/ic_clear_input.webp
    - assets/images/ic_new_group.webp
    - assets/images/ic_add_friend1.webp
    - assets/images/ic_group_list.webp
    - assets/images/ic_file.webp
    - assets/images/ic_menu_download.webp
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
